// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnGb0qtovDuc25F95etsCkelJodVuhrGE',
    appId: '1:1023867656590:web:b8ba01220f745677132cdf',
    messagingSenderId: '1023867656590',
    projectId: 'kaizenteam-ba827',
    authDomain: 'kaizenteam-ba827.firebaseapp.com',
    storageBucket: 'kaizenteam-ba827.firebasestorage.app',
    measurementId: 'G-074V1KYKS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9XHt-ck8IoHzFTK8Nib80iCrdI1NZBuI',
    appId: '1:1023867656590:android:5248c80c21a37293132cdf',
    messagingSenderId: '1023867656590',
    projectId: 'kaizenteam-ba827',
    storageBucket: 'kaizenteam-ba827.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA_zPVRt1D_CKCLkvJezteou5iiM3secw',
    appId: '1:1023867656590:ios:118b76b47cc8390d132cdf',
    messagingSenderId: '1023867656590',
    projectId: 'kaizenteam-ba827',
    storageBucket: 'kaizenteam-ba827.firebasestorage.app',
    iosBundleId: 'com.example.kaizenteam',
  );
}
